name: Auto Merge Feature Branches

on:
  push:
    branches:
      - 'feature/*'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge feature branch into main
        run: |
          FEATURE_BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Merging $FEATURE_BRANCH into main"
          git fetch origin $FEATURE_BRANCH
          git merge origin/$FEATURE_BRANCH --no-edit || exit 1
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
